#pragma once

/* Generated by src/assets/convert_fonts.py. */

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#elif defined(LV_LVGL_H_INCLUDE_SYSTEM)
#include <lvgl.h>
#else
#include "lvgl/lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(font_noto_sans_sc_semibold_12);
LV_FONT_DECLARE(font_noto_sans_sc_semibold_14);
LV_FONT_DECLARE(font_noto_sans_sc_semibold_18);
LV_FONT_DECLARE(font_noto_sans_jp_semibold_12);
LV_FONT_DECLARE(font_noto_sans_jp_semibold_14);
LV_FONT_DECLARE(font_noto_sans_jp_semibold_18);

#ifdef __cplusplus
}
#endif
