#!/usr/bin/env python3

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[2]
FONTS_DIR = ROOT_DIR / "assets" / "fonts"
OUTPUT_DIR = Path(__file__).resolve().parent / "res_c"
DECLARATIONS_PATH = Path(__file__).resolve().parent / "assets.h"
CONFIG_PATH = FONTS_DIR / "font_config.json"
MARKER = "/* Generated by src/assets/convert_fonts.py. */"


def find_font_converter() -> str:
    configured = os.environ.get("LV_FONT_CONV")
    if configured:
        return configured
    executable = shutil.which("lv_font_conv")
    if executable:
        return executable
    raise FileNotFoundError(
        "Cannot find lv_font_conv. Install it or set LV_FONT_CONV to its executable path."
    )


def encoded_symbols(specification: dict) -> str:
    encoding = specification["encoding"]
    symbols: list[str] = []
    for first_row, last_row in specification["rows"]:
        for row in range(first_row, last_row + 1):
            for cell in range(1, 95):
                try:
                    symbols.append(bytes([0xA0 + row, 0xA0 + cell]).decode(encoding))
                except UnicodeDecodeError:
                    continue
    return "".join(dict.fromkeys(symbols))


def converter_args(target: dict, source: Path, output: Path) -> list[str]:
    arguments = [
        "--no-compress",
        "--no-prefilter",
        "--force-fast-kern-format",
        "--size",
        str(target["size"]),
        "--bpp",
        str(target.get("bpp", 4)),
        "--font",
        str(source),
    ]
    for font_range in target.get("ranges", []):
        arguments.extend(["-r", font_range])
    combined_symbols = "".join(
        encoded_symbols(item) for item in target.get("encoded_ranges", [])
    )
    symbols = "".join(dict.fromkeys(combined_symbols))
    if symbols:
        arguments.extend(["--symbols", symbols])
    arguments.extend(["--format", "lvgl", "-o", str(output)])
    return arguments


def generate_target(converter: str, target: dict, temporary_dir: Path) -> Path:
    source = FONTS_DIR / target["source"]
    if not source.is_file():
        raise FileNotFoundError(f"Font source does not exist: {source}")

    output = OUTPUT_DIR / f"{target['name']}.c"
    temporary_output = temporary_dir / output.name
    subprocess.run(
        [converter, *converter_args(target, source, temporary_output)], check=True
    )

    content = temporary_output.read_text().rstrip() + "\n"
    content = content.replace(str(temporary_output), output.relative_to(ROOT_DIR).as_posix())
    content = content.replace(str(source), source.relative_to(ROOT_DIR).as_posix())
    content = f"{MARKER}\n{content}"
    if not output.exists() or output.read_text() != content:
        output.write_text(content)
        print(f"updated {output.relative_to(ROOT_DIR)}")
    else:
        print(f"unchanged {output.relative_to(ROOT_DIR)}")
    return output


def update_declarations(targets: list[dict]) -> None:
    lines = [
        "#pragma once",
        "",
        MARKER,
        "",
        "#if defined(LV_LVGL_H_INCLUDE_SIMPLE)",
        '#include "lvgl.h"',
        "#elif defined(LV_LVGL_H_INCLUDE_SYSTEM)",
        "#include <lvgl.h>",
        "#else",
        '#include "lvgl/lvgl.h"',
        "#endif",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    lines.extend(f"LV_FONT_DECLARE({target['name']});" for target in targets)
    lines.extend(
        [
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
        ]
    )
    content = "\n".join(lines)
    if not DECLARATIONS_PATH.exists() or DECLARATIONS_PATH.read_text() != content:
        DECLARATIONS_PATH.write_text(content)
        print(f"updated {DECLARATIONS_PATH.relative_to(ROOT_DIR)}")
    else:
        print(f"unchanged {DECLARATIONS_PATH.relative_to(ROOT_DIR)}")


def main() -> int:
    config = json.loads(CONFIG_PATH.read_text())
    targets = config.get("targets", [])
    converter = find_font_converter()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="music-fonts-") as temporary:
        expected = {
            generate_target(converter, target, Path(temporary)) for target in targets
        }

    for output in OUTPUT_DIR.glob("font_*.c"):
        if output not in expected and output.read_text(errors="ignore").startswith(MARKER):
            output.unlink()
            print(f"removed {output.relative_to(ROOT_DIR)}")
    update_declarations(targets)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
